=== ashwindasr/programming/xml/letter.dtd
<!-- DTD document for letter.xml -->

<!ELEMENT letter (contact,salutation,subject,body,closing,signature) >

<!ELEMENT contact (name,phone,flag) >
  <!ATTLIST contact type CDATA #IMPLIED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT flag EMPTY>
  <!ATTLIST flag gender (M | F) "M" >
<!ELEMENT salutation (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT body (#PCDATA)>
<!ELEMENT closing (#PCDATA)>
<!ELEMENT signature (#PCDATA)>

=== ashwindasr/programming/xml/letter.xml
<?xml version = "1.0"?>

<!-- A letter marked up with XML -->
<!DOCTYPE letter SYSTEM "letter.dtd" >
<letter>
  <contact>
    <name>Ash</name>
    <phone>1234567890</phone>
    <flag gender="M" />
  </contact>
  <salutation>Respected Sir,</salutation>
  <subject>Reimbursment Request</subject>
  <body>
    This letter is for the request of reimbursment for the business trip on 1/1/19. PFA the receipts for the entire trip.
  </body>
  <closing>Regards</closing>
  <signature>Ash</signature>
</letter>
